name: publish

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=,priority=100
            type=sha,prefix=,priority=80
            type=ref,event=branch,priority=60
            type=ref,event=pr,priority=40

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: src/.
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          file: "src/GordonBeemingCom/Dockerfile"

  deployPreview:
    name: "Deploy to Preview"
    needs: build
    concurrency:
      group: preview
      cancel-in-progress: false
    environment:
      name: "preview"
      url: "https://preview.gordonbeeming.com/"
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:    
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy Web App to Preview
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
              TAG=$(echo 'https://ghcr.io/${{ github.repository }}:${{ github.sha }}' | tr '[:upper:]' '[:lower:]')
              az webapp config container set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --docker-custom-image-name $TAG
              
      - name: Azure Logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
              

  deployLive:
    name: "Deploy to live"
    needs: deployPreview
    concurrency:
      group: live
      cancel-in-progress: false
    environment:
      name: "live"
      url: "https://gordonbeeming.com/"
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:    
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy Web App to Live
        uses: Azure/cli@v1.0.7
        with:
          inlineScript: |
              TAG=$(echo 'https://ghcr.io/${{ github.repository }}:${{ github.sha }}' | tr '[:upper:]' '[:lower:]')
              az webapp config container set --resource-group ${{ secrets.AZURE_WEBAPP_RG }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --docker-custom-image-name $TAG
              
      - name: Azure Logout
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
              